# Sorting in Pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sample_data/SuperMarket Analysis.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [6]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [9]:
df["Total"] = df["Sales"] + df["Tax 5%"]

In [10]:
branch_sorted = df.groupby('Branch')
branch_sorted

In [11]:
branch_sorted = df.sort_values(by="Total", ascending=False)
branch_sorted

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Total
350,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2/15/2019,2:53:00 PM,Credit card,993.00,4.761905,49.6500,6.6,1092.300
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,4:20:00 PM,Credit card,989.80,4.761905,49.4900,8.7,1088.780
557,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,8:23:00 PM,Ewallet,985.20,4.761905,49.2600,4.5,1083.720
699,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,4:18:00 PM,Ewallet,975.00,4.761905,48.7500,8.0,1072.500
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4,1071.180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,236-86-3015,Giza,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2/4/2019,1:38:00 PM,Ewallet,13.98,4.761905,0.6990,9.8,15.378
443,192-98-7397,Giza,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,1/8/2019,2:11:00 PM,Ewallet,12.78,4.761905,0.6390,9.5,14.058
223,279-62-1445,Giza,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2/21/2019,12:38:00 PM,Cash,12.54,4.761905,0.6270,8.2,13.794
629,308-39-1707,Alex,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,1/26/2019,6:19:00 PM,Credit card,12.09,4.761905,0.6045,8.2,13.299
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9,11.187

In [12]:
top_rated = df.sort_values(by="Rating")
top_rated

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Total
876,885-56-0389,Giza,Naypyitaw,Member,Male,Fashion accessories,52.35,1,2.6175,54.9675,2/12/2019,5:49:00 PM,Cash,52.35,4.761905,2.6175,4.0,57.585
328,730-61-8757,Cairo,Mandalay,Member,Male,Health and beauty,51.13,4,10.2260,214.7460,1/25/2019,10:11:00 AM,Credit card,204.52,4.761905,10.2260,4.0,224.972
379,182-69-8360,Cairo,Mandalay,Normal,Female,Electronic accessories,23.65,4,4.7300,99.3300,1/30/2019,1:32:00 PM,Credit card,94.60,4.761905,4.7300,4.0,104.060
72,510-95-6347,Cairo,Mandalay,Member,Female,Food and beverages,48.52,3,7.2780,152.8380,3/5/2019,6:17:00 PM,Ewallet,145.56,4.761905,7.2780,4.0,160.116
85,730-50-9884,Giza,Naypyitaw,Member,Female,Sports and travel,83.06,7,29.0710,610.4910,3/5/2019,2:31:00 PM,Ewallet,581.42,4.761905,29.0710,4.0,639.562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,423-57-2993,Cairo,Mandalay,Normal,Male,Sports and travel,93.39,6,28.0170,588.3570,3/27/2019,7:18:00 PM,Ewallet,560.34,4.761905,28.0170,10.0,616.374
853,866-70-2814,Cairo,Mandalay,Normal,Female,Electronic accessories,52.79,10,26.3950,554.2950,2/25/2019,11:58:00 AM,Ewallet,527.90,4.761905,26.3950,10.0,580.690
62,347-34-2234,Cairo,Mandalay,Member,Female,Sports and travel,55.07,9,24.7815,520.4115,2/3/2019,1:40:00 PM,Ewallet,495.63,4.761905,24.7815,10.0,545.193
387,725-56-0833,Alex,Yangon,Normal,Female,Health and beauty,32.32,10,16.1600,339.3600,2/20/2019,4:49:00 PM,Credit card,323.20,4.761905,16.1600,10.0,355.520
60,285-68-5083,Giza,Naypyitaw,Member,Female,Sports and travel,24.74,3,3.7110,77.9310,2/15/2019,5:47:00 PM,Credit card,74.22,4.761905,3.7110,10.0,81.642

In [13]:
df_index = df.set_index("Invoice ID")
df_index.rank(method='average')

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Total
Invoice ID,,,,,,,,,,,,,,,,,
750-67-8428,170.5,830.5,283.0,286.0,598.5,712.0,653.5,814.0,814.0,302.5,297.5,828.0,814.0,500.5,814.0,856.5,814.0
226-31-3081,836.5,496.5,783.0,286.0,85.5,51.0,453.5,145.0,145.0,979.0,49.5,172.5,145.0,500.5,145.0,938.0,145.0
631-41-3108,170.5,830.5,783.0,286.0,754.5,397.0,653.5,618.0,618.0,906.5,316.0,500.0,618.0,500.5,618.0,579.5,618.0
123-19-1176,170.5,830.5,283.0,286.0,598.5,534.0,747.0,766.0,766.0,226.5,968.0,828.0,766.0,500.5,766.0,739.5,766.0
373-73-7910,170.5,830.5,283.0,286.0,917.5,832.0,653.5,867.0,867.0,636.5,65.0,828.0,867.0,500.5,867.0,216.0,867.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233-67-5758,836.5,496.5,783.0,786.0,598.5,338.0,56.5,55.0,55.0,253.5,355.0,828.0,55.0,500.5,55.0,366.0,55.0
303-96-2227,506.5,166.5,783.0,286.0,754.5,954.0,941.0,996.0,996.0,787.5,666.0,828.0,996.0,500.5,996.0,77.0,996.0
727-02-1313,170.5,830.5,283.0,786.0,435.5,240.0,56.5,38.0,38.0,649.0,312.5,172.5,38.0,500.5,38.0,629.5,38.0
347-56-2442,170.5,830.5,783.0,786.0,754.5,607.0,56.5,104.0,104.0,493.0,528.5,172.5,104.0,500.5,104.0,20.0,104.0
849-09-3807,170.5,830.5,283.0,286.0,259.5,853.0,653.5,870.0,870.0,445.0,325.5,172.5,870.0,500.5,870.0,440.5,870.0

In [16]:
product_revenue = df.groupby("Product line")["Total"].sum().sort_values(ascending=False)
product_revenue

Product line
Food and beverages        58818.408
Sports and travel         57747.723
Electronic accessories    56925.033
Fashion accessories       56891.890
Home and lifestyle        56426.766
Health and beauty         51536.298
Name: Total, dtype: float64

In [20]:
product_revenue.rank(method='dense', ascending=False)

Product line
Food and beverages        1.0
Sports and travel         2.0
Electronic accessories    3.0
Fashion accessories       4.0
Home and lifestyle        5.0
Health and beauty         6.0
Name: Total, dtype: float64

In [21]:
product_revenue.rank(method='average', ascending=False)

Product line
Food and beverages        1.0
Sports and travel         2.0
Electronic accessories    3.0
Fashion accessories       4.0
Home and lifestyle        5.0
Health and beauty         6.0
Name: Total, dtype: float64